# Generated by Django 4.1 on 2022-08-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Потяг')),
                ('travel_time', models.SmallIntegerField(verbose_name='Час прибуття')),
                ('from_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_town_set', to='cities.city', verbose_name='З міста')),
                ('to_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_town_set', to='cities.city', verbose_name='до міста')),
            ],
            options={
                'verbose_name': 'Потяг',
                'verbose_name_plural': 'Потяги',
                'ordering': ['travel_time'],
            },
        ),
    ]
