# Generated by Django 4.1 on 2022-08-12 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Маршрут')),
                ('travel_time', models.SmallIntegerField(verbose_name='Час прибуття')),
                ('from_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from_town_set', to='cities.city', verbose_name='З міста')),
                ('to_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to_town_set', to='cities.city', verbose_name='до міста')),
                ('trains', models.ManyToManyField(to='trains.train', verbose_name='Потяги')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
                'ordering': ['travel_time'],
            },
        ),
    ]
